### ISSUE TITLE
newline characters in subject headers break the queue

### ISSUE THREAD

**Issue by kmohrf** [pinax/django-mailer#100]
hi,

I’ve just come across an exception in our error logging handler that is caused by an email header that contains newlines. The actual exception happens in [engine.py#L155](https://github.com/pinax/django-mailer/blob/1.2.5/mailer/engine.py#L155): `BadHeaderError: Header values can't contain newlines (got '[redacted] foo\r\n bar' for header 'Subject')` and is raised by djangos `forbid_multi_line_headers` function from `django.core.mail.message`. It seems like the fault is with the mail client but it would be nice if django-mailer could handle this kind of error.

My quick fix is this short function I’ve added to the `mailer.models` module and used as a decorator on the `db_to_email` function:

```python
def normalize_subject(func):
    from functools import wraps
    import re
    @wraps(func)
    def decorator(*args, **kwargs):
        email = func(*args, **kwargs)
        if email is not None:
            email.subject = re.sub(r'[\n\r]', '', email.subject)
        return email
    return decorator
```
But I’m not quite sure this is the way to fix this for good. Maybe pickle allows for some preprocessing before saving the email or there is an entirely different approach I didn’t think of. If you have any idea how to move forward from this I’ll gladly work on the code and submit a pull request.

Thank you!

**Comment by spookylukey** [comment]
Thanks for the suggestion. One of the design aims of django-mailer is to have the same API as Django's builtin mailing functions. You should be able to drop django-mailer in (or out) without changing your code. This kind of sanitising belongs in Django core mail functions. If they throw errors (and I think they do so deliberately), then so should django-mailer. So I think this means that the sanitising belongs in your code that puts the email together - in fact the documentation states this explicitly: https://docs.djangoproject.com/en/dev/topics/email/#preventing-header-injection
