### ISSUE TITLE
Protect against loop from EMAIL_BACKEND equal to MAILER_EMAIL_BACKEND?

### ISSUE THREAD

**Issue by moseb** [pinax/django-mailer#108]
Hi!

I had a situation where `MAILER_EMAIL_BACKEND` and `EMAIL_BACKEND` were both set to `mailer.backend.DbBackend` (with version 1.2.4). The symptom is that sending mails does not seem to work, until you notice that there is new rows in the database.

I was wondering if that's a scenario you consider worth protecting against. What do you think?

Best, Sebastian

**Comment by spookylukey** [comment]
It sounds like you could protect against it easily enough by simply raising `AssertionError` when the settings are used, if the two values are equal. I'd be happy to accept a patch that did this. It will probably be hard to write a test, so a test is not necessary.
