### ISSUE TITLE
Aware datetime support

### ISSUE THREAD

**Issue by amosjyng** [pinax/django-mailer#11]
This needs support for aware datetimes in Django 1.5.

     venv/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:827: RuntimeWarning: DateTimeField received a naive datetime (2013-04-14 15:33:29.242280) while time zone support is active.
      RuntimeWarning)

Also, is this project still even alive? Seems like nobody's been replying to any of the issues, or been actively maintaining the code, either.

**Comment by paltman** [comment]
Agreed, @bsnux. This issue seems resolved but deferring to either @spookylukey or @amosjyng to close this out.

**Comment by spookylukey** [comment]
I think this was fixed in 887ec2c9d8e05d061293b56ff913a9b293c42aa0
