### ISSUE TITLE
Document or fix DontSendEntry

### ISSUE THREAD

**Issue by pakal** [pinax/django-mailer#111]
We would expect the DontSendEntry table to be used to filter-out recipients from pending messages, but actually it's only used when directly sending messages through mailer, not when mailer is used as an alternate EMAIL_BACKEND for django. 
And it seems that if the recipients list becomes empty, the email is scheduled anyway.

**Comment by spookylukey** [comment]
Agreed.

This behaviour comes from before django-mailer was an EMAIL_BACKEND - when that didn't even in exist in Django.

I'd be happy to accept a patch to either fix it - by adding the filtering to the backend, as long as it preserves backwards compatibility for people who are not using the EMAIL_BACKEND - or document the current behaviour.

**Comment by pakal** [comment]
Eventually django-mailer didn't fit my needs so I went for another solution, but here is a little PR just to warn people : https://github.com/pinax/django-mailer/pull/112/files

**Comment by pakal** [comment]
Thanks for merging, this ticket can be closed I guess?   B-)

**Comment by spookylukey** [comment]
Yes. Someone may actually be motivated to provide a fix in the future, but they can open a new ticket. Thanks!
