### ISSUE TITLE
Opt in lock file creation in case of running in a container.

### ISSUE THREAD

**Issue by tsudmi** [pinax/django-mailer#117]
When running cronjobs as containers on different nodes, the lock file does not make much sense.
It would be nice to disable lock file creation with an environment variable.
You also need to grant permission for creating files to the containers, otherwise, you will get the following error:
```
lockfile.LockFailed: failed to create /src/cronjob-send-mail-1576067280-t2wvg-b2c4740.14099116249141749430
```

**Comment by spookylukey** [comment]
Yep, a setting to control this would be good. Unfortunately we can't just use `MAILER_LOCK_PATH = None` because that is already the default, and implies a default path. A new setting like `MAILER_USER_FILE_LOCK` would work. I'm not likely to work on a patch for this myself.
