### ISSUE TITLE
engine.py raises DatabaseError, not NotSupportedError using MySQL on python 3.7.4

### ISSUE THREAD

**Issue by scoopseven** [pinax/django-mailer#120]
We're using mysql with python 3.7.4. Rather than raising a NotSupportedError, because MySQL doesn't support nowait=True. 

Changed: 
```
except NotSupportedError:
```
to:
```
except (NotSupportedError, DatabaseError):
```

**Comment by spookylukey** [comment]
It looks like you must be using an old version of django-mailer, the code you mentioned has already been changed, and I think the change may have fixed your issue. Can you try the latest version and see if this is still a problem?

**Comment by spookylukey** [comment]
Please re-open is there is still an issue, thanks.
