### ISSUE TITLE
Allow purging unsuccessful message logs

### ISSUE THREAD

**Issue by stinovlas** [pinax/django-mailer#124]
**Is your feature request related to a problem? Please describe.**
I recently discovered that `purge_mail_log` command only purges message logs with result 1 `SUCCESS`. My application sends tons of mails each day and the message log table has bloated considerably since the old unsuccessful message logs are not purged regularly.

**Describe the solution you'd like**
I suggest adding an option to the `purge_mail_log` command allowing purging of message logs with other results than 1 `SUCCESS`. Current behaviour should be preserved in case that no option is provided.

If you like the idea, I can create a pull request.

**Comment by spookylukey** [comment]
Sounds like a good feature, a PR would be great.
