### ISSUE TITLE
Error creating RPM

### ISSUE THREAD

**Issue by assuncap** [pinax/django-mailer#13]
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    long_description=open('docs/usage.txt').read(),
IOError: [Errno 2] No such file or directory: 'docs/usage.txt'
error: Bad exit status from /var/tmp/rpm-tmp.zLe4Dn (%build)

**Comment by spookylukey** [comment]
I don't know what is being done to produce this error - a full description is needed. Nevertheless, I think this is fixed by cb03c73460679b69832ee86180c78d3f764cba63
