### ISSUE TITLE
Fallback email sender

### ISSUE THREAD

**Issue by rodrigoegimenez** [pinax/django-mailer#134]
Hi!

We've recently started using this package and implemented on top of it the possibility to specify an alternative email server as backup in case the main sending mechanism fails.

After reading [this PR](https://github.com/pinax/django-mailer/pull/22) I wanted to check with you first if it might be of use for the package to have this addition. The commit is [this one](https://github.com/doppiozerosrl/django-mailer/commit/097584d262dcde7bc16c703fdaa1beea43f608f8), the idea is basically set up two additional settings variables: MAILER_FALLBACK_EMAIL_BACKEND and EMAIL_FALLBACK_CONFIG which, if present, are used in case the main sending mechanism fails. 

If it makes an useful addition let me know and I'll send a pull request.

**Comment by spookylukey** [comment]
As before, I think this is best handled by a backend that implements the "fallback strategy". So you have:

- django_mailer, which provides a mail backend that saves things to the DB for later sending
   - and requires a single other backend to actually do the sending
- a "fallback strategy" backend that is either hardcoded to use 2 different backends, or could be configured to use a list of other backends.
- you then point MAILER_EMAIL_BACKEND at your "fallback strategy" backend

Structured this way, you can compose the behaviours you want very nicely, without having to tie any of these together. So, for example, your "fallback strategy" backend could be used without django-mailer at all. 

If there is some reason this won't work, please let me know.
