### ISSUE TITLE
What is the purpose of send_loop

### ISSUE THREAD

**Issue by jaap3** [pinax/django-mailer#136]
I noticed the function `send_loop` `mailer.engine`:

https://github.com/pinax/django-mailer/blob/2228d2b8107996fb46074999a0af77caeda3b430/src/mailer/engine.py#L263-L273

It doesn't seem to be documented but it is configurable and is tested.

I was looking for a way to have the mailer check the queue more frequently than the 1 minute limitation inherent to cron, and `send_loop` seems like a perfect way to do so.

Is it safe for me to write a management command that basically just starts the `send_loop` function and have it run in the background (managed by something like supervisord)? Or should I copy over the `send_loop` function in case it goes away?

Would a PR with a management command that starts the `send_loop` function be accepted to this project?

[P.S.] A minor tweak to the function would be to replace `while not Message.objects.all(): ` with `while not Message.objects.all().exists()`:

**Comment by jaap3** [comment]
I added a management command (`runmailer`) and got it running in the background. Seems to work just fine, for reference, this is the management command:

```python
import sys

from datetime import datetime

from mailer.engine import send_loop

from django.core.management import BaseCommand


class Command(BaseCommand):
    """Start the django-mailer send loop"""

    def handle(self, *args, **options):
        self.stdout.write(datetime.now().strftime('%B %d, %Y - %X'))
        self.stdout.write('Starting django-mailer send loop.')
        quit_command = 'CTRL-BREAK' if sys.platform == 'win32' else 'CONTROL-C'
        self.stdout.write('Quit the loop with %s.' % quit_command)
        send_loop()
```

**Comment by jaap3** [comment]
For reference. In the past users have filed issue #99 and #56 looking for a way to get around the 1 minute delay when using cron.

**Comment by spookylukey** [comment]
I was unaware of that function! :blush:  It does look like it's intended to be used just as you have.

This looks like it could be a good addition to django-mailer, if it came with docs.
