### ISSUE TITLE
Please start with the "why?" and the benefits

### ISSUE THREAD

**Issue by guettli** [pinax/django-mailer#141]
If I look at this page: https://pypi.org/project/django-mailer/ 

I see:

> First, add “mailer” to your INSTALLED_APPS in your settings.py. Run ./manage.py migrate to install models.

Please imagine you found this page on you want to know what this application is about.

Wouldn't it be nice to read what your project is about?

My feature request: Start with the "why?" and the benefits if you application.

**Comment by spookylukey** [comment]
Good call, will address soon.

**Comment by spookylukey** [comment]
This will only appear on the next release.
