### ISSUE TITLE
Condense logging

### ISSUE THREAD

**Issue by daveisfera** [pinax/django-mailer#145]
**Is your feature request related to a problem? Please describe.**
Logs are overly verbose (3 logs that could/should be a single log)

**Describe the solution you'd like**
Do a single log and put the data in `extra`, like this:
```
logger.info("Sent", extra={'sent': sent, 'deferred': deferred, 'duration': time.time() - start_time})
```

**Describe alternatives you've considered**
Do a single log with all of the data, like this:
```
logger.info("%s sent; %s deferred; %.2f seconds" % (sent, deferred, time.time() - start_time))
```

**Comment by spookylukey** [comment]
I'm assuming you're talking about - https://github.com/pinax/django-mailer/blob/fd1c3f96fd517608f93901a84cba454917b41486/src/mailer/engine.py#L258  . This sounds like a good change, I'd accept a patch

**Comment by daveisfera** [comment]
```
diff --git a/src/mailer/engine.py b/src/mailer/engine.py
index 56b36c1..a1df242 100644
--- a/src/mailer/engine.py
+++ b/src/mailer/engine.py
@@ -255,9 +255,7 @@ def send_all():
         if use_file_lock:
             release_lock(lock)

-    logger.info("")
-    logger.info("%s sent; %s deferred;" % (counts['sent'], counts['deferred']))
-    logger.info("done in %.2f seconds" % (time.time() - start_time))
+    logger.info("Sent", extra={'sent': sent, 'deferred': deferred, 'duration': time.time() - start_time})


 def send_loop():
```
