### ISSUE TITLE
send_loop busy loops when there are deferred messages

### ISSUE THREAD

**Issue by mikaraunio** [pinax/django-mailer#146]
`send_loop` only sleeps between iterations if the message queue is totally empty. When there are deferred messages waiting to be retried, it will loop continuously, filling logs in the process if loglevel is `INFO` or `DEBUG`.

Unable to file a PR right anyway, however believe the fix would be to change the sleep condition from: `while not Message.objects.all().exists():` to `while not Message.objects.non_deferred().exists():`

**Comment by spookylukey** [comment]
Agreed, that would be a good fix.
