### ISSUE TITLE
feature request: release email(s) from admin under interface under Message actions

### ISSUE THREAD

**Issue by steverweber** [pinax/django-mailer#167]
Would be nice to release email to be sent from the admin interface under the "Messages" actions.

This is a nice to have on testing / staging servers where the cronjob is disabled or not setup as protection from sending emails to potential real users.

**Comment by spookylukey** [comment]
Sounds reasonable - I'd accept a PR that added an [admin action](https://docs.djangoproject.com/en/4.2/ref/contrib/admin/actions/) that triggered sending of the selected emails.

**Comment by steverweber** [comment]
sure. done. bufor a do a PR im not sure how to handle translations... is it fine if I leave that incomplete but wired up to be done..
```
messages.add_message(request, messages.INFO, _("Message(s) sent."))
```
