### ISSUE TITLE
Lock Failed

### ISSUE THREAD

**Issue by andrewfam** [pinax/django-mailer#23]
Hey all,

Getting the following error running manage.py and no way of knowing how to debug this. Anyone has any advice?

acquiring lock...
LockFailed:

**Comment by spookylukey** [comment]
I think the above solution is probably correct, therefore closing.

**Comment by abodacs** [comment]
where django-mailer creates the lock ??

**Comment by spookylukey** [comment]
@abodacs  It creates is in the directory that is the current working directory when you call the manage.py command (I think)
