### ISSUE TITLE
Print actual unpickled subject and body in LogMessage admin

### ISSUE THREAD

**Issue by umrashrf** [pinax/django-mailer#29]
I need to see who the email was sent and what it contained. It'd be useful to show actual unpickled EmailMessage in admin page.

It's an easy change as far as I see it.

**Comment by spookylukey** [comment]
The recipient and subject are displayed in the changelist.

Displaying the contents of the message is only easy if you have plain text only emails.

A patch for these would be accepted

**Comment by spookylukey** [comment]
I've fixed this on master now.
