### ISSUE TITLE
ask github to make this repo the main repo

### ISSUE THREAD

**Issue by benkonrath** [pinax/django-mailer#37]
It should be possible to get github (through a support request) to make this repo the main repo. This would change the display from this:

```
pinax/django-mailer
forked from jtauber/django-mailer 
```
to just this:
```
pinax/django-mailer
```
This would be more clear to everybody using and contributing to this project. Thanks!

**Comment by spookylukey** [comment]
I've filed a support request as indicated.

**Comment by benkonrath** [comment]
Thanks!
