### ISSUE TITLE
Schedule emails

### ISSUE THREAD

**Issue by illing2005** [pinax/django-mailer#42]
Is it possible to use django-mailer to schedule emails?
What I need is to be able to set a `when_to_send` field in the message model of django-mailer.
Maybe one could use the `when_added` field to achieve this?
Is anything like this planed?

My use case is that I want to send out an email when a new comment is created. But the email should be sent 10 minutes after the comment is created.

**Comment by spookylukey** [comment]
This is the same as pull request #6
