### ISSUE TITLE
send_email not sending emails

### ISSUE THREAD

**Issue by psychok7** [pinax/django-mailer#43]
HI, i am having some trouble sending queued emails with `django-mailer=1.1` and `django==1.7.x` i call the `send_email` command and nothing happens. There are no errors and the email does not go.

Any ideas?

**Comment by psychok7** [comment]
it looks like the issue is happending somewhere here in the `send_all()`:

```
    acquired, lock = acquire_lock()
    if not acquired:
        return
```

for some reason it now aquiring the `lock`

**Comment by spookylukey** [comment]
The lock file is called "send_mail.lock". https://github.com/pinax/django-mailer/blob/master/mailer/engine.py#L76, in your current directory. You will need to delete this.

**Comment by psychok7** [comment]
@spookylukey there is no `send_mail.lock` in my current directory and i even get a `lockfile.NotLocked: send_mail is not locked`

**Comment by psychok7** [comment]
@spookylukey `send_mail.lock` is not being created for me to delete it and i do have permissions to write to that folder

**Comment by spookylukey** [comment]
It sounds like either you are looking in the wrong directory, or you've found a bug in  lockfile. https://pypi.python.org/pypi/lockfile

**Comment by psychok7** [comment]
@spookylukey i was looking at `lockfile` source code and i found something interesting:

in the `aquire()` function in the `os.link()` it's giving me `OSError: [Errno 1] Operation not permitted`

i changed it to shutil.copy2 just for testing and it worked so for some reason `os.link()` its not doing what is supposed to do.

I am sure i am in the right directory because i can see the temporary unique file being generated, it just not able to `os.link()` and i have no clue why (permissions should be right).

I saw some other recommended locking python apps like https://pypi.python.org/pypi/zc.lockfile for example maybe i am going to give it a try

**Comment by psychok7** [comment]
Ok i think i finally got to the bottom of this. So i am using Vagrant 1.7.4 but there appears to be a bug with the symlink creation as reported here https://github.com/mitchellh/vagrant/issues/713 

If i do os.link() outside my vagrant it works so i am assuming django-mailer will work too

**Comment by psychok7** [comment]
@spookylukey i created a PR with a detailed explanation of how i solved my problem and some code to allow an alternative locking system provided by lockfile as well.
