### ISSUE TITLE
send_mail and send_html_mail should include "cc" and "bcc" fields

### ISSUE THREAD

**Issue by subramanyamVemu** [pinax/django-mailer#47]
It will be good to have send_mail and send_html_mail include "cc" and "bcc" fields

**Comment by spookylukey** [comment]
We aim to match the signature of send_mail in Django:

https://docs.djangoproject.com/en/1.8/topics/email/#send-mail

Please see those docs if you want to use BCC - you can do the same with django-mailer by using the `EmailMessage` class and setting `EMAIL_BACKEND`
