### ISSUE TITLE
smtplib.SMTPDataError 503 error blocks the entire queue in send_mail

### ISSUE THREAD

**Issue by andrewebdev** [pinax/django-mailer#48]
So if there is any exception raised for one email in the Queue, all subsequent mails are essentially blocked. Often times this leads to a backlog of emails that would then need to be verified and sent. Needless to say customers gets a bit annoyed at this.

I Feel that the expected behaviour is to log the error, mark the emails as "cannot send" or something like that, and then continue with the rest of the emails.

**Comment by spookylukey** [comment]
By '500 error' I assume you mean an exception - 500 errors are to do with HTTP, and there is no HTTP in this scenario I think - unless you are using an email backend that uses HTTP. What specific exception are you seeing?

We do already catch certain exceptions and mark the email to defer:

https://github.com/pinax/django-mailer/blob/master/mailer/engine.py#L137

If you are using a different backend, we can't know which exceptions to catch, so this is tricky to solve.

**Comment by andrewebdev** [comment]
yeah sorry it's _not_ HTTP; it's SMTP

    smtplib.SMTPDataError: (503, '5.5.1 RCPT first. wb11sm4488998wic.16 - gsmtp')

Basically it was a invalid email address for one of the emails. This causes the entire Queue to be blocked (50+ emails in one day) just because of one invalid entry.

I'm using the DB backend.

**Comment by spookylukey** [comment]
I meant which actual backend for sending email - I presume you are using the default SMTP if you are getting those errors.

Since we already catch similar exceptions, I've added this to the list, so this bug should be fixed in 28a317e4446a16427cfd9f1034fa16453758210b
