### ISSUE TITLE
Plain text body: <Can't decode>

### ISSUE THREAD

**Issue by mikeshultz** [pinax/django-mailer#49]
When adding a message via the Django admin, not all of the form displays.  It appears to stop at the 'Plain text body'  field and just displays "&lt;Can't decode&gt;".  No fields follow.

I tried setting it up via pip as well as the master branch on github.  Running django 1.8.3 with python 3.4.3.

I haven't been able to look into this further yet.  I'm hoping someone has already seen this issue before I start digging too far into django-mailer's guts.

**Comment by spookylukey** [comment]
You can't add messages via the admin - only as per the usage instructions. I'll clarify them a bit to make it more obvious.

**Comment by mikeshultz** [comment]
Well, that explains it.  Maybe I was oblivious, but I did not see any mention of that in the docs.  I just made the incorrect assumption that you could send out E-mails to your users from the admin.

Thanks.
