### ISSUE TITLE
email message should update extra_headers after sending email to reflect any headers updated by the mail server

### ISSUE THREAD

**Issue by subramanyamVemu** [pinax/django-mailer#50]
In mailer/engine.py 
After sending the email with
130:                    email.send()

To capture the information if the mail server has updated extra_headers like in amazon SES 
is it a good idea to update the email like 

131: message.email = email
132: message.save()

**Comment by spookylukey** [comment]
This sounds like something that should be captured by MessageLog.objects.log. I think your line 131 should be enough - this will preserve the original Message as it was created, and will also store a record of what was sent in MessageLog.

A patch for this would be accepted.

**Comment by spookylukey** [comment]
I'll commit a fix for this soon

**Comment by subramanyamVemu** [comment]
Thank you !!
As always your response is pretty fast :+1:
