### ISSUE TITLE
sending email without delay?

### ISSUE THREAD

**Issue by benkonrath** [pinax/django-mailer#56]
Is it possible to use this package and send emails without the 1 minute delay imposed by the cronjob?

Most of the time the delay is fine but there are few circumstances like password reset and activation where I'd want the email to be sent out immediately. I'd still want the message log and the queue for failed connections. Is there a way to do this? I looked over the docs but couldn't find anything. 

Thanks for your work on this package; it's really useful!

**Comment by ossanna16** [comment]
@benkonrath Would you mind joining our Pinax project Slack channel (http://slack.pinaxproject.com) and asking your question there? We're usually able to answer questions in Slack quicker :)

**Comment by benkonrath** [comment]
Sure, no problem.

**Comment by ossanna16** [comment]
Thank you!
