### ISSUE TITLE
Error ! When adding first message and clicking save and continue editing.

### ISSUE THREAD

**Issue by ArtemBernatskyy** [pinax/django-mailer#62]
Here how it [looks like ](https://drive.google.com/open?id=0B045JEsT1LHncXNzdTdQS0RsTDA).
And [here is the output](http://pastebin.com/giDCD09c) . Sorry folks for challenging admin url (

**Comment by spookylukey** [comment]
It looks like you are trying to add a message via the Django admin. Please see the usage directions here: https://github.com/pinax/django-mailer/blob/master/docs/usage.rst#usage

However, this bug can stay open as UX bug - we should probably prevent people attempting to use the admin to create messages.
