### ISSUE TITLE
Can't send HTML emails

### ISSUE THREAD

**Issue by elimisteve** [pinax/django-mailer#7]
I've got some (simple) code that implements this I can push soon if people are interested.

**Comment by paltman** [comment]
It might be worth adding documentation for how to do this @spookylukey.  Perhaps this is the action item for this issue–documented example.

**Comment by spookylukey** [comment]
Django docs already have this info, and we already have a documented `send_html_mail` utility. However, I've re-organized `usage.txt` to make this more obvious, with links to Django docs, which we do not need to reproduce.

I've also renamed docs to `*.rst` so they get displayed nicely by GitHub. We could also explore using readthedocs.org, but I think there is little need now.

**Comment by kaldown** [comment]
"Django docs already have this info, and we already have a documented send_html_mail utility. Where is that doc ?
