### ISSUE TITLE
Pip version does not support Django 1.10

### ISSUE THREAD

**Issue by marteinn** [pinax/django-mailer#70]
Hi! 
Just wanted to check when a version that supports Django 1.10 will be out on pip?

Thanks!

**Comment by ossanna16** [comment]
@spookylukey Can you help with this please?

**Comment by davidszotten** [comment]
have you considered using something like travis to build and upload to pypi: https://docs.travis-ci.com/user/deployment/pypi/

i have had pretty good success using that in the past, and it might make it possible to have more people do releases

**Comment by spookylukey** [comment]
I've just released 1.2.2, fixing this.

@davidszotten - thanks for the tip, although looking at it, it doesn't look easier that the current process, which is very easy and documented, especially given that you need to give them your PyPI username and password, and then ensure that tags are only used for releases etc. etc. AFAICS It is much easier just to add people to PyPI to allow them to release. I'll leave it to the Pinax team to deal with people volunteering to be maintainers.
