### ISSUE TITLE
Encode error with non unicode chars

### ISSUE THREAD

**Issue by burzillibus** [pinax/django-mailer#75]
If subject has non unicode chars, the mailer throws an encode error at the engine.py

Below my corrections on my installed package:
`             
                    try:
                        logging.info("sending message '{0}' to {1}".format(
                        message.subject.encode("utf-8"),
                        u", ".join(message.to_addresses).encode("utf-8"))
                        )
                    except:
                        logging.info("sending message '{0}' to {1}".format(
                            message.subject,
                            ", ".join(message.to_addresses))
                        )
`

**Comment by spookylukey** [comment]
I need more information to understand your bug:

1) What do you mean by non-unicode characters? There aren't any non-unicode characters that should be making it this far into your app.

2) What version of Python, django and django-mailer are you using?

3) For you changes, it is always better to send a diff to make it clear what it was changed from and to.

**Comment by spookylukey** [comment]
I have checked the code and it seems to work on both Python 2 and 3. However, the line you highlighted could be handled better, so I've also pushed a commit that improves it - https://github.com/pinax/django-mailer/commit/9e94f60654c95c477be046a445e6f89092ac74f7 . Please let me know if you still have problems - post a traceback, and the data that causes it to go wrong.

**Comment by burzillibus** [comment]
Hi Luke,
sorry if my previous issue comment was uncompleted. 
In my case I've a subject like "Attività del giorno" and the char 'à' rises the error.
My configuration is:
- Django==1.8.8
- django-mailer==1.1
- mailer==0.8.1
- python 2.7

I can't upgrade mailer because it upgrade even Django, and the application isn't compliant with the new   one :'(
I saw your commit and it's working for me. 

Thank you very much

**Comment by spookylukey** [comment]
There is no problem using django-mailer with Django 1.8.8. I think you probably did:

    pip install --upgrade django-mailer

This upgrades everything that django-mailer depends on. However, if you do:

    pip install django-mailer==1.2.2

you should have no problem - it won't upgrade Django. You can also install from VCS https://pip.pypa.io/en/stable/reference/pip_install/#git

**Comment by spookylukey** [comment]
The code you've edited was already changed since 1.1, with tests showing that it works with unicode. Please upgrade to the latest version:

    pip install django-mailer==1.2.2
