### ISSUE TITLE
Multiple mail connection

### ISSUE THREAD

**Issue by salvorapi** [pinax/django-mailer#79]
Hi,

my django application use multiple account for send mail using `connection` parameter of `send_mail` function.

I see code of extension and use the default django mail settings.
But, in my config settings I have something like:

```
EMAIL_CONNECTIONS = {
    'default': {
        'from_email':'default@server.com',
        'host': 'smtp.server.com',
        'username': 'usr',
        'password': 'pwd',
        'use_tls': True,
    },
    'info': {
        'from_email':'default@server.com',
        'host': 'smtp.server.com',
        'username': 'usr',
        'password': 'pwd',
        'use_tls': True,
    },
}
```

How can I use django-mailer with multiple account ?

Salvo.

**Comment by spookylukey** [comment]
I'm afraid I can't understand your question. EMAIL_CONNECTIONS is not a standard Django setting. Are you using an extension that uses this? If so, please let me know what this extension is, or show more of your code that is actually using this.

**Comment by salvorapi** [comment]
You're right. EMAIL_CONNECTIONS  is a custom setting of my app that I use to define multiple mail config and assign to `connection` param on send_mail function (https://docs.djangoproject.com/en/1.10/topics/email/#send-mail).

I've used this solution because I need to send mail from different account.
Now, my problem is that in case SMTP fail the mail is lost and your solution is perfect because store mail in DB and delivery is managed by cron job. 

But I need to use different SMTP account. 
Do you think it's possible ?

Thank you.

Salvo.

**Comment by spookylukey** [comment]
It depends on how you decide which connection to use.

First, work out whether it is possible to write your custom connection/send_mail logic as a custom email backend - https://docs.djangoproject.com/en/1.10/topics/email/#defining-a-custom-email-backend - this will be possible, for example, if you can tell just by examining the message (e.g. the from/to address) which SMTP details are needed. If the decision of which backend to use is made using contextual information from the calling code that isn't stored in the message itself, you will have difficulties.

If if it possible, then after writing that backend and refactoring your code to use it, you then simply install django-mailer and use a custom backend as described here https://github.com/pinax/django-mailer/blob/master/docs/usage.rst#usage :

    EMAIL_BACKEND = "mailer.backend.DbBackend"
    MAILER_EMAIL_BACKEND = "your.custom.EmailBackend"

**Comment by salvorapi** [comment]
Yes, I think to use `from_address` to route mail over multiple account.
I didn't see the `MAILER_EMAIL_BACKEND` setting. Can be perfect for what I need to do.

Thank you.

Salvo.

**Comment by manishkapikad** [comment]
@salvorapi   Thank you for an amazing project. 
Just had an question how i can generate dynamaic connection(smtp servers,emal,password)  while sending email out using
`from mailer import send_mail` , For example 

`from django.core.mail import send_mail`
function  takes argument "connection" where i can dynamically generate connection and i can use ithis connection in send_mail.  

I do dymanic conncection 

`from django.core.mail import get_connection`
connection = get_connection(host=email_smtp_host,
                                    port=email_smtp_port,
                                    username=smtp_email_box_user,
                                    password=smtp_email_box_pass,
                                    use_tls=email_smtp_tls
                                    )
send_email(subject_part, text_part,text_part, sender or settings.DEFAULT_FROM_EMAIL, recipients,connection=connection)
`

"`from mailer import send_mail`" also takes `MAILER_EMAIL_BACKEND` in setting but if i want to use multiple connection email address and password how i can do using `MAILER_EMAIL_BACKEND`

As per my understanding MAILER_EMAIL_BACKEND going to use defined SMTP servers and Email and password.

**Comment by manishkapikad** [comment]
@salvorapi  Im really Sorry for bugging you.

Is Django-mailer support from `EmailMultiAlternatives`

**Comment by manishkapikad** [comment]
@spookylukey Thank you for an amazing project.
Just had a question how I can generate dynamic connection(SMTP servers, email, password) while sending an email out using
from mailer import send_mail, For example

from django.core.mail import send_mail
the function takes argument "connection" where I can dynamically generate connection and I can use this connection in send_mail.

I do dynamic connection

from django.core.mail import get_connection
connection = get_connection(host=email_smtp_host, port=email_smtp_port, username=smtp_email_box_user, password=smtp_email_box_pass, use_tls=email_smtp_tls )
send_email(subject_part, text_part,text_part, sender or settings.DEFAULT_FROM_EMAIL, recipients,connection=connection)
`

"from mailer import send_mail" also takes MAILER_EMAIL_BACKEND in setting but if I want to use multiple connection email address and password how I can do using MAILER_EMAIL_BACKEND

As per my understanding MAILER_EMAIL_BACKEND going to use defined SMTP servers and Email and password.
