### ISSUE TITLE
TypeError: sequence item 0: expected str instance, tuple found

### ISSUE THREAD

**Issue by hellvix** [pinax/django-mailer#86]
I can see some e-mails are sent, however, this error is persistent after running `manage.py send_email`.

```
class EmailThread(threading.Thread):
    def __init__(self, subject, context, recipient, template):
        self.subject = subject
        self.recipient = recipient
        self.message = get_template(template).render(context)
        threading.Thread.__init__(self)

    def run(self):
        msg = EmailMessage(
            subject=self.subject + " (DEBUG)" if settings.DEBUG else self.subject,
            from_email=settings.DEFAULT_DO_NOT_REPLY,
            to=self.recipient,
            body=self.message
        )
        msg.content_subtype = "html"

        try:
            msg.send(fail_silently=False)
            log.info("E-mail triggered. Subject: '%s', to: %s" % (self.subject, self.recipient))
        except Exception as e:
            log.exception(e)


def notify_admin_blocked_account(user):
    """
    Sends sends an email when the account is blocked
    :return:
    """
    email = EmailThread(
        subject='{}, your account has been blocked'.format(user),
        context={
            'user': user,
            'login_attempts': settings.MAX_STAFF_PWD_ATTEMPTS,
        },
        recipient=[user.email,],
        template='mail/notify_admin_blocked_account.html'
    )
    email.start()
```

```
python manage.py send_mail
------------------------------------------------------------------------
acquiring lock...
acquired.
releasing lock...
released.
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/documents/envs/atomenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/documents/envs/atomenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/documents/envs/atomenv/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/documents/envs/atomenv/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/documents/envs/atomenv/lib/python3.5/site-packages/mailer/management/commands/send_mail.py", line 26, in handle
    send_all()
  File "/documents/envs/atomenv/lib/python3.5/site-packages/mailer/engine.py", line 133, in send_all
    u", ".join(message.to_addresses).encode("utf-8"))
TypeError: sequence item 0: expected str instance, tuple found

```

Django 1.11.3
Python 3.5.2

**Comment by spookylukey** [comment]
Could you reduce this to a minimal test case, preferably in the form of a test that could be added to our test suite, so we can see what is going on. It seems very strange. Please also include what version of Django/Python you are using, and test against the latest version of django-mailer. Thanks

**Comment by hellvix** [comment]
This is pretty minimal. I am basically sending a normal e-mail, but through a thread. 

Anyways, the problem doesn't seem to be there, for I get no exceptions when scheduling the e-mail. It does appear, however when I call the management command.

I am betting it might be something wrong with my versions:

Django **1.11.3**
Python **3.5.2**

**Comment by spookylukey** [comment]
I suspect you have bad data in your DB from previous code that looked different, and passed a tuple instead of a string

**Comment by hellvix** [comment]
I've just installed `django-mailer`. So the DB was pretty clean.

**Comment by spookylukey** [comment]
I've added a test based on your code, in branch test_issue_86 . It passes fine if run it like so:

    ./runtests.py mailer.tests.TestIssue86

(with running the whole test suite there are other errors, likely related to threading + Django's test setup)

I've tried on Django 1.11 with Python 3.5, and other versions.

So, something else is going on, as I said. I cannot see a bug in django-mailer here. Please re-open if you can show a bug in django-mailer.

**Comment by spookylukey** [comment]
@hellvix I meant to mentioned before:

If you are using theading to do asynchronous/background sending of the mail:

1. It is unnecessary - that is what django-mailer is itself for. The only thing django-mailer does when you `send` is saves a pickled object into a database table.

2. Using threading from within a web request context is almost certainly not what you want. First, you *must* call the `Thread.join` method, otherwise there is no guarantee your thread will run, and the only place to put that `Thread.join` call is within the request processing lifecycle, and it blocks, which means you are mainly back where you started - or at least, the gains are minimal. This is why we have solutions like Celery for async/background processing.

**Comment by hellvix** [comment]
You are right.

I removed and reinstalled `django-mailer`. It works. No idea what might have caused the problem, but I also had a clean install before.

Anyways, thanks for the help.

**Comment by hellvix** [comment]
```
python manage.py send_mail
------------------------------------------------------------------------
acquiring lock...
acquired.
releasing lock...
released.
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/web/sites/envs/app/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/web/sites/envs/app/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/web/sites/envs/app/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/web/sites/envs/app/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/web/sites/envs/app/lib/python3.6/site-packages/mailer/management/commands/send_mail.py", line 26, in handle
    send_all()
  File "/home/web/sites/envs/app/lib/python3.6/site-packages/mailer/engine.py", line 144, in send_all
    ", ".join(message.to_addresses))
TypeError: sequence item 0: expected str instance, tuple found
```

I got this error again. I am assuming a bad-parsed e-mail was added to the database. I tried to list all e-mails in the `mailer.message` table, however I could see nothing abnormal. The addresses seem to be fine. 

Any tips in how to debug this easily? This problem is only happening in production so it's a bit of a problem to replicate.

```
class Email:
    def __init__(self, subject, context, recipient, template, attachments=list({})):
        self.subject = subject
        self.recipient = recipient
        self.message = get_template(template).render(context)
        self.attachments = attachments

    def dispatch(self):
        msg = EmailMessage(
            subject=self.subject + " (DEBUG)" if settings.DEBUG else self.subject,
            from_email=settings.DEFAULT_DO_NOT_REPLY,
            to=self.recipient,
            body=self.message
        )
        msg.content_subtype = "html"

        # file, filename and mime type
        for attachment in self.attachments:
            msg.attach(
                content=attachment['content'].read(),
                filename=attachment['filename'],
            )

        try:
            with transaction.atomic():
                msg.send(fail_silently=False)
            log.info("E-mail triggered. Subject: '%s', to: %s" % (self.subject, self.recipient))
        except Exception as e:
            if not settings.DEBUG:
                log.exception(e)
            else:
                raise

def mail_user_lis_file(lis_req, file):
    email = Email(
        subject='Your  {}'.format(
            lis_req.get_lis_name()
        ),
        recipient=[lis_req.customer.email, ],
        template='mail/notify_user_lis_file.html',
        attachments=[
            {
                'content': file,
                'filename': 'lis.txt',
                'mimetype': 'text/plain'
            },
        ]
    )
    email.dispatch()
```

**Comment by spookylukey** [comment]
I'm guessing you are passing bad data to the `to` parameter of `EmailMessage`. It should be a list of email addresses - https://docs.djangoproject.com/en/2.1/topics/email/#emailmessage-objects

I'm guessing in your `Email(recipient=)` parameter you are passing a list of tuples - perhaps:

    [('Administrators', 'admins@domain.com')]

instead of:

    ['admins@domain.com']

(I can't tell because I can't see what `lis_req.customer.email` is

which is then passed to `EmailMessage`, causing this error.
