### ISSUE TITLE
Encoding Problems

### ISSUE THREAD

**Issue by welworx** [pinax/django-mailer#88]
I found some problems with encoding of the title that occurred by calling admin/mailer/message/14/change/.

After adding 
```
from django.utils.encoding import python_2_unicode_compatible
```
to the models.py file and the decorator to each class which contains a `__str__` solved this problem.

**Comment by spookylukey** [comment]
This bug appears to have already been fixed in 89560adca629a55c688fd30f56f9f6f592d1851b
