### ISSUE TITLE
immediately sending email

### ISSUE THREAD

**Issue by AbrahamLara** [pinax/django-mailer#99]
Is there a way to circumvent having to run an external command to send emails every 1 minute using cron? I want to be able to send an email immediately.

Is there an alternative to this?

**Comment by spookylukey** [comment]
You could:

1) call `mailer.engine.send_all` manually to send all queued emails. However, this kind of defeats the object of having a queue, and brings back all the pains of synchronous email sending that django-mailer is trying to avoid
2) don't use django-mailer, or at least don't configure it as your default backend
3) directly import the `send_mail` functions and use them as appropriate:

    import mailer as queued_mail
    from django.core import mail as immediate_mail

    queued_mail.send_mail(subject, ....)
    immediate_mail.send_mail(subject, ....)

**Comment by Hafnernuss** [comment]
Note, for this to work, I had to specify the `connection` manually:

```python
connection = immediate_mail.get_connection(settings.MAILER_EMAIL_BACKEND)
immediate_mail.mail_admins(subject, message, connection=connection)
```
